---
title: Maximum Likelihood Estimation of the Spatial Durbin Model
author: Nicola Kollmann
date: '2020-07-03'
categories:
  - Econometrics
tags:
  - R code
  - spatial
output: blogdown::html_page
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<style>
body {
text-align: justify}
</style>
<p>This is an R Markdown document that documents my solution to the first assignment in the “Regression Analysis for Spatial Data” course. The course was taught by Professor Dr. Roland Füss and Dr. Zeno Adams as part of the GSERM Summer School 2020.</p>
<ol style="list-style-type: lower-alpha">
<li>Use a maximum likelihood framework to estimate the Spatial Durbin Model <span class="math inline">\(Y = \rho WY + X\beta + \lambda WX + \epsilon\)</span>, with house price growth as the dependent variable <span class="math inline">\(Y\)</span>, and an intercept and the growth rate in the housing stock as the regressors <span class="math inline">\(X\)</span>. Use the same neighborhood weight matrix <span class="math inline">\(W\)</span> for both, <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>. Interpret the economic impact of the results. <em>Hint</em>: check for NAs in the data using <code>is.na()</code> and replace them with zeros using <code>ifelse()</code> or <code>replace()</code>.</li>
</ol>
<div id="load-the-dataset-of-house-prices-in-switzerland" class="section level4">
<h4>Load the dataset of house prices in Switzerland</h4>
<p>The first step in any data analysis is to set the working directory and load the necessary data into the dataframe <code>dat1</code>. To get a first idea about the data set we also provide a short glimpse into the first 6 observations below. As one can see we are dealing with cross-sectional data of the 106 Swiss MS regions (MS = mobilité spatiale) in the year 2009.</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:left;">
MS.name
</th>
<th style="text-align:right;">
dlhp
</th>
<th style="text-align:right;">
dlpop
</th>
<th style="text-align:right;">
dlstock
</th>
<th style="text-align:right;">
v
</th>
<th style="text-align:right;">
udl
</th>
<th style="text-align:right;">
hp
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:left;">
Zürich
</td>
<td style="text-align:right;">
0.0286198
</td>
<td style="text-align:right;">
0.00967
</td>
<td style="text-align:right;">
0.0059643
</td>
<td style="text-align:right;">
0.0005261
</td>
<td style="text-align:right;">
62.87112
</td>
<td style="text-align:right;">
852000
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:left;">
Glattal-Furttal
</td>
<td style="text-align:right;">
0.0440826
</td>
<td style="text-align:right;">
0.02309
</td>
<td style="text-align:right;">
0.0107927
</td>
<td style="text-align:right;">
0.0091841
</td>
<td style="text-align:right;">
31.82254
</td>
<td style="text-align:right;">
655000
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:left;">
Limmattal
</td>
<td style="text-align:right;">
0.0504704
</td>
<td style="text-align:right;">
0.01989
</td>
<td style="text-align:right;">
0.0280132
</td>
<td style="text-align:right;">
0.0080083
</td>
<td style="text-align:right;">
35.18333
</td>
<td style="text-align:right;">
744000
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:left;">
Knonaueramt
</td>
<td style="text-align:right;">
0.0489526
</td>
<td style="text-align:right;">
0.02030
</td>
<td style="text-align:right;">
0.0222473
</td>
<td style="text-align:right;">
0.0099034
</td>
<td style="text-align:right;">
16.94226
</td>
<td style="text-align:right;">
646000
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:left;">
Zimmerberg
</td>
<td style="text-align:right;">
0.0431495
</td>
<td style="text-align:right;">
0.00836
</td>
<td style="text-align:right;">
0.0111485
</td>
<td style="text-align:right;">
0.0046613
</td>
<td style="text-align:right;">
29.23505
</td>
<td style="text-align:right;">
849000
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:left;">
Pfannenstiel
</td>
<td style="text-align:right;">
0.0055299
</td>
<td style="text-align:right;">
0.00911
</td>
<td style="text-align:right;">
0.0070467
</td>
<td style="text-align:right;">
0.0129980
</td>
<td style="text-align:right;">
30.30976
</td>
<td style="text-align:right;">
937000
</td>
</tr>
</tbody>
</table>
<p>Following the hint from the exercise description I check for missing values, but it seems like they have been taken care of beforehand in the data cleaning process.</p>
<pre class="r"><code>any(is.na(dat1))</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>The variables of interest in the analysis are <code>dlhp</code> (<span class="math inline">\(Y\)</span>) and <code>dlstock</code> (<span class="math inline">\(X\)</span>). The former is the difference in logged house prices, which represents the house price growth and the latter is the difference in logged housing stock, which corresponds to the growth rate in the housing stock. Due to their transformations we have to interpret the results accordingly as percentage changes.</p>
</div>
<div id="create-the-weight-matrix-w" class="section level4">
<h4>Create the weight matrix <span class="math inline">\(W\)</span></h4>
<p>In order to create the weight matrix <span class="math inline">\(W\)</span>, we need a package that can read the shape file for Switzerland. This package is called <code>rgdal</code> and I load it into my work space with the following command: <code>library(rgdal)</code>.</p>
<p>Now it only needs one command to read the shapefile into the working environment.</p>
<pre class="r"><code>CH &lt;- readOGR(&quot;.&quot;, &quot;MS_Gebiete&quot;)</code></pre>
<pre><code>## OGR data source with driver: ESRI Shapefile 
## Source: &quot;/Users/nicolakollmann/R/Website_Tranquilpeak/content/post&quot;, layer: &quot;MS_Gebiete&quot;
## with 106 features
## It has 4 fields
## Integer64 fields read as strings:  ge11_ms_id</code></pre>
<p>With this shapefile it is fairly easy to construct a k-nearest neighbor weight matrix. Following the logic from the tutorial sessions I will work with <span class="math inline">\(k=6\)</span> and also change the object class from <code>knn</code> to <code>nb</code> and finally to <code>matrix</code>. These steps require yet another package called <code>spdep</code>, which is also loaded into my work space. At the end of the following code we are left with the weight matrix <span class="math inline">\(W\)</span> in the appropriate object class <code>matrix</code>.</p>
<pre class="r"><code>nearest.six &lt;- knearneigh(coordinates(CH), k = 6, RANN = FALSE)
class(nearest.six)</code></pre>
<pre><code>## [1] &quot;knn&quot;</code></pre>
<pre class="r"><code>nearest.six2 &lt;- knn2nb(nearest.six)
class(nearest.six2)</code></pre>
<pre><code>## [1] &quot;nb&quot;</code></pre>
<pre class="r"><code>W &lt;- nb2mat(nearest.six2)
class(W)</code></pre>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>It is illustrative to look at a small excerpt from the weight matrix to check what these commands have produced so far. Otherwise the process of generating the weight matrix remains kind of a black box.</p>
<pre><code>##                    Zürich Glattal-Furttal Limmattal Knonaueramt Zimmerberg
## Zürich          0.0000000       0.1666667 0.1666667   0.1666667  0.0000000
## Glattal-Furttal 0.1666667       0.0000000 0.1666667   0.0000000  0.0000000
## Limmattal       0.1666667       0.1666667 0.0000000   0.1666667  0.0000000
## Knonaueramt     0.1666667       0.0000000 0.1666667   0.0000000  0.1666667
## Zimmerberg      0.1666667       0.1666667 0.0000000   0.1666667  0.0000000</code></pre>
<p>The weight matrix is a sparse matrix with many 0 entries. Especially, the entries on the main diagonal have to be 0, due to the fact that no region can be a direct neighbor of itself. All entries that are non-zero correspond to the choice of <span class="math inline">\(k\)</span>. In this exercise the choice of <span class="math inline">\(k=6\)</span> put an entry of 1 into the combination of regions that are k-nearest neighbors. However, the weight matrix needs to be transformed into a row-stochastic matrix, where all rows sum up to 1. This transformation changes all non-zero entries to <span class="math inline">\(\frac{1}{6} = 0.1666667\)</span>.</p>
</div>
<div id="spatial-durbin-model-sdm" class="section level4">
<h4>Spatial Durbin Model (SDM)</h4>
<p>In the tutorial sessions we have seen three methods of estimating a spatial model using the maximum likelihood framework:</p>
<ol style="list-style-type: decimal">
<li>Full Maximum Likelihood<br />
</li>
<li>Concentrated Maximum Likelihood<br />
</li>
<li>using the <code>spdep</code> package</li>
</ol>
<p>In this assignment I will show the full maximum likelihood estimation and also the results from the <code>spdep</code> package to confirm my approach.</p>
<div id="setup" class="section level5">
<h5>Setup</h5>
<p>To set up the maximum likelihood estimation, I need to assign the variables. As specified by the exercise description, the dependent variable <span class="math inline">\(Y\)</span> is the growth rate of housing prices and the growth rate in the housing stock enters into the model as the regressor <span class="math inline">\(X\)</span>, together with an intercept. Moreover, since we want to estimate a Spatial Durbin Model we also assign a spatial lag to the growth rate in the housing stock <span class="math inline">\(WX\)</span>. Intuitively, I expect that the growth in the housing stock has a negative impact on the growth in house prices, due to more supply. It would, however, be interesting to include the vacancy rate into the model for further investigation.</p>
<pre class="r"><code>Y &lt;- as.matrix(dat1$dlhp)
colnames(Y) &lt;- &quot;DLHP&quot;
X &lt;- cbind(1, dat1$dlstock)
colnames(X) &lt;- c(&quot;intercept&quot;, &quot;DLSTOCK&quot;)
WX &lt;- W%*%dat1$dlstock</code></pre>
</div>
<div id="full-maximum-likelihood-estimation" class="section level5">
<h5>Full Maximum Likelihood Estimation</h5>
<p>First, we need to specify the likelihood function that we want to maximize.</p>
<pre class="r"><code>normal.lik1 &lt;- function(theta, y, X) {
  beta &lt;- theta[1:2]
  sigma &lt;- theta[3]
  rho &lt;- theta[4]
  lambda &lt;- theta[5]
  n &lt;- nrow(X)
  In &lt;- diag(n) 
  # log-likelihood:
  logl &lt;- log(det(In - rho*W)) - (n/2)*log(2*pi*sigma^2) - sum((1/(2*sigma^2))*(y - rho*W%*%y - X%*%beta - lambda*WX)^2)
  return(-logl)
}</code></pre>
<p>The corresponding maximum likelihood is then easy to find with an optimizer, where we only need to specify the starting values and plug in the assigned variables.</p>
<pre class="r"><code>fit.sdm &lt;- optim(c(1, 1, 1, 0.5, 0.5), normal.lik1, y = Y, X = X, method = &quot;BFGS&quot;, 
              control = list(maxit = 1000, trace = TRUE))</code></pre>
<pre><code>## initial  value 159.094564 
## iter  10 value -208.557251
## iter  20 value -217.685641
## final  value -217.708734 
## converged</code></pre>
</div>
<div id="spatial-regression-package" class="section level5">
<h5>Spatial Regression Package</h5>
<p>To confirm the findings from the previous section I estimate the same model with the spatial regression package <code>spdep</code>.</p>
<pre class="r"><code>W_listw &lt;- nb2listw(nearest.six2)
fit.sdm &lt;- lagsarlm(dlhp ~ dlstock, W_listw, data = dat1, Durbin = TRUE, method = &quot;eigen&quot;, quiet = TRUE)
summary(fit.sdm)</code></pre>
<pre><code>## 
## Call:spatialreg::lagsarlm(formula = formula, data = data, listw = listw, 
##     na.action = na.action, Durbin = Durbin, type = type, method = method, 
##     quiet = quiet, zero.policy = zero.policy, interval = interval, 
##     tol.solve = tol.solve, trs = trs, control = control)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -0.1595652 -0.0133322  0.0051518  0.0189610  0.0764884 
## 
## Type: mixed 
## Coefficients: (asymptotic standard errors) 
##               Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)  0.0296288  0.0083892  3.5318 0.0004128
## dlstock     -0.2490728  0.1145049 -2.1752 0.0296140
## lag.dlstock  0.0730572  0.1595267  0.4580 0.6469799
## 
## Rho: 0.31094, LR test value: 4.8282, p-value: 0.027997
## Asymptotic standard error: 0.14648
##     z-value: 2.1227, p-value: 0.033779
## Wald statistic: 4.5058, p-value: 0.033779
## 
## Log likelihood: 217.7088 for mixed model
## ML residual variance (sigma squared): 0.00094912, (sigma: 0.030808)
## Number of observations: 106 
## Number of parameters estimated: 5 
## AIC: -425.42, (AIC for lm: -422.59)
## LM test for residual autocorrelation
## test value: 0.40978, p-value: 0.52208</code></pre>
<p>The following table shows that both estimation methods produce the same results.</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Full Maximum Likelihood Estimation
</th>
<th style="text-align:center;">
Estimation with package
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:center;">
0.030
</td>
<td style="text-align:center;">
0.030
</td>
</tr>
<tr>
<td style="text-align:left;">
beta
</td>
<td style="text-align:center;">
-0.249
</td>
<td style="text-align:center;">
-0.249
</td>
</tr>
<tr>
<td style="text-align:left;">
rho
</td>
<td style="text-align:center;">
0.311
</td>
<td style="text-align:center;">
0.311
</td>
</tr>
<tr>
<td style="text-align:left;">
lambda
</td>
<td style="text-align:center;">
0.073
</td>
<td style="text-align:center;">
0.073
</td>
</tr>
<tr>
<td style="text-align:left;">
LogLikelihood
</td>
<td style="text-align:center;">
217.709
</td>
<td style="text-align:center;">
217.709
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="economic-interpretation" class="section level4">
<h4>Economic Interpretation</h4>
<p>First of all, since we are especially interested in the spatial dependence in the model it is important to mention that <span class="math inline">\(\rho\)</span> is not particularly high with a value of 0.311. It seems like there is some spatial dependence in the growth rate of house prices, but it does not seem to be the main effect. This is important to keep in mind when we look at the different average effects in the next step of the analysis, since it implies a rather low average indirect effect. The coefficient of -0.249 for <code>dlstock</code> can be interpreted as the elasticity between the growth rate in house prices and the growth rate in housing stock. Thus, a 1% increase in the growth rate of housing prices results in a 0.249% decrease in the growth rate of house prices. This is in line with my expectations stated earlier. Moreover, the average growth rate in house prices in our data set is around 3.1%. A 0.249% decrease, therefore, approximately corresponds to a 8% drop in house price growth. However, it needs to be stressed that this only corresponds to the <strong>average direct effect</strong>, without taking into account indirect effects such as spillover and feedback effects. In order to make more sophisticated statements with regard to these effects, we next compute them separately.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Compute the direct, indirect, and total impacts of house price growth (see p. 34–39 in LeSage and Pace, 2009).</li>
</ol>
<p>Again, we can manually compute the impacts and confirm the results with the package estimation.</p>
<pre class="r"><code>n &lt;- nrow(dat1)
In &lt;- diag(n)
rho &lt;- fit.sdm$rho
beta &lt;- as.matrix(fit.sdm$coefficients)

SW &lt;- solve(In - rho*W)%*%(In*beta[2] + W*beta[3])
row.names(SW) &lt;- dat1$MS.name ; colnames(SW) &lt;- dat1$MS.name</code></pre>
<pre class="r"><code># &#39;average direct effect&#39;
M2_dir &lt;- 1/n*sum(diag(SW)) ; M2_dir</code></pre>
<pre><code>## [1] -0.2492912</code></pre>
<p>The value above corresponds to the coefficient for the growth rate in housing stock we discussed earlier and thus, provides for a nice sanity check of the results.</p>
<pre class="r"><code># &#39;average total effect&#39;
iota &lt;- as.matrix(rep(1, n))
M2_tot &lt;- 1/n*t(iota)%*%SW%*%iota ; M2_tot</code></pre>
<pre><code>##            [,1]
## [1,] -0.2554442</code></pre>
<pre class="r"><code># &#39;average indirect effect&#39;
M2_indir &lt;- M2_tot - M2_dir ; M2_indir</code></pre>
<pre><code>##              [,1]
## [1,] -0.006153025</code></pre>
<pre class="r"><code># with the &#39;spdep&#39; package
coefs &lt;- impacts(fit.sdm, listw = W_listw, R = 500) ; coefs</code></pre>
<pre><code>## Impact measures (mixed, exact):
##             Direct     Indirect      Total
## dlstock -0.2492912 -0.006153025 -0.2554442</code></pre>
<p>With the package estimation we also easily get a nice summary of the impacts:</p>
<pre class="r"><code>summary(coefs, short = TRUE, zstats = TRUE)</code></pre>
<pre><code>## Impact measures (mixed, exact):
##             Direct     Indirect      Total
## dlstock -0.2492912 -0.006153025 -0.2554442
## ========================================================
## Simulation results (asymptotic variance matrix):
## ========================================================
## Simulated standard errors
##            Direct  Indirect     Total
## dlstock 0.1151372 0.1892713 0.1596665
## 
## Simulated z-values:
##            Direct   Indirect     Total
## dlstock -2.206071 0.07324008 -1.504002
## 
## Simulated p-values:
##         Direct   Indirect Total  
## dlstock 0.027379 0.94162  0.13258</code></pre>
<p>Again, both methods lead to the same results, as one would expect.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Investigate the impact of an increase in the housing stock growth to 10% in the following regions: Basel-Stadt, Unteres Baselbiet, Oberes Baselbiet, Zürich, Zimmerberg, Pfannenstiel, Genève, Lausanne. Plot a map that shows the response of house price changes and their spatial diffusion.</li>
</ol>
</div>
<div id="first-step-get-fitted-values" class="section level4">
<h4>First step: get fitted values</h4>
<p>This can be done with the following equation: <span class="math inline">\(E(Y_1) = (I_n-\rho W)^{-1}(X_1\beta + WX_1 \lambda)\)</span></p>
<pre class="r"><code>X1 &lt;- cbind(1, dat1$dlstock)
fitted1 &lt;- solve(In - rho*W)%*%(X1%*%beta[c(1,2)]+WX*beta[3])</code></pre>
</div>
<div id="second-step-introduce-a-shock-to-regressor-matrix-and-get-the-updated-fitted-values" class="section level4">
<h4>Second step: introduce a shock to regressor matrix and get the updated fitted values</h4>
<p>Again, we use the following equation to compute the updated values: <span class="math inline">\(E(Y_2) = (I_n-\rho W)^{-1}(X_2\beta + WX_2 \lambda)\)</span></p>
<pre class="r"><code>X2 &lt;- X1
row.names(X2) &lt;- dat1$MS.name
# shock the regions Basel-Stadt, Unteres Baselbiet, Zürich, Zimmerberg, Pfannenstiel, Genève and Lausanne 
# (set dlstock to 0.1)
X2[c(&quot;Basel-Stadt&quot;, &quot;Unteres Baselbiet&quot;, &quot;Zürich&quot;, &quot;Zimmerberg&quot;, &quot;Pfannenstiel&quot;, &quot;Genève&quot;, &quot;Lausanne&quot;),  2] &lt;- 0.1 
fitted2 &lt;- solve(In - rho*W)%*%(X2%*%beta[c(1,2)]+W%*%X2[ , 2]*beta[3])</code></pre>
</div>
<div id="third-step-plot-the-shock-as-the-difference-ey2---ey1-on-a-map." class="section level4">
<h4>Third step: plot the shock as the difference <span class="math inline">\(E(Y2) - E(Y1)\)</span> on a map.</h4>
<p>The following map shows the response of house price changes and their spatial diffusion:</p>
<p><img src="/post/2020-07-04-Maximum-Likelihood-Estimation-of-the-Spatial-Durbin-Model_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>As expected from the low value for <span class="math inline">\(\rho\)</span> and the minuscule average indirect effects there is not much spatial diffusion to be observed in the map. The effects are quiet concentrated in the origin of the shock but do not show a strong spillover to the neighboring regions. This can further be confirmed if we look at the regions where the effect was at least 0.01 in magnitude.</p>
<pre class="r"><code>effect.table &lt;- as.data.frame(effect[effect &lt;=-0.01, ])
colnames(effect.table) &lt;- &quot;effect [absolute percentage changes]&quot;</code></pre>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
effect [absolute percentage changes]
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Zürich
</td>
<td style="text-align:center;">
-2.353
</td>
</tr>
<tr>
<td style="text-align:left;">
Glattal-Furttal
</td>
<td style="text-align:center;">
-0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Limmattal
</td>
<td style="text-align:center;">
-0.011
</td>
</tr>
<tr>
<td style="text-align:left;">
Knonaueramt
</td>
<td style="text-align:center;">
-0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Zimmerberg
</td>
<td style="text-align:center;">
-2.232
</td>
</tr>
<tr>
<td style="text-align:left;">
Pfannenstiel
</td>
<td style="text-align:center;">
-2.334
</td>
</tr>
<tr>
<td style="text-align:left;">
Zürcher Oberland
</td>
<td style="text-align:center;">
-0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Winterthur
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Zürcher Unterland
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Laufental
</td>
<td style="text-align:center;">
-0.018
</td>
</tr>
<tr>
<td style="text-align:left;">
Einsiedeln
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
March
</td>
<td style="text-align:center;">
-0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Zug
</td>
<td style="text-align:center;">
-0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Thal
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Basel-Stadt
</td>
<td style="text-align:center;">
-2.636
</td>
</tr>
<tr>
<td style="text-align:left;">
Unteres Baselbiet
</td>
<td style="text-align:center;">
-2.468
</td>
</tr>
<tr>
<td style="text-align:left;">
Oberes Baselbiet
</td>
<td style="text-align:center;">
-0.018
</td>
</tr>
<tr>
<td style="text-align:left;">
Baden
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Mutschellen
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Freiamt
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Fricktal
</td>
<td style="text-align:center;">
-0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
Lausanne
</td>
<td style="text-align:center;">
-2.196
</td>
</tr>
<tr>
<td style="text-align:left;">
Nyon
</td>
<td style="text-align:center;">
-0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Genève
</td>
<td style="text-align:center;">
-2.825
</td>
</tr>
</tbody>
</table>
</div>
